spring:
  application:
    name: blogapi

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:sqlite:./data/blog.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    root: INFO